# Generated by Django 3.1.3 on 2022-02-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(help_text='Category Name', max_length=255)),
                ('category_desc', models.TextField(help_text='Category Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayLists',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(help_text='PlayList Name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('playlist_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.categories')),
            ],
            options={
                'verbose_name': 'PlayList',
                'verbose_name_plural': 'PlayLists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YoutubeImporter',
            fields=[
                ('yt_importer_id', models.AutoField(primary_key=True, serialize=False)),
                ('yt_video_id', models.CharField(help_text='Video id from Youtube', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('yt_video_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories')),
                ('yt_video_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playlists')),
            ],
            options={
                'verbose_name': 'YoutubeImporter',
                'verbose_name_plural': 'YoutubeImporter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(help_text='PlayList Name', max_length=255)),
                ('video_desc', models.TextField(help_text='Video Description')),
                ('video_yt_id', models.CharField(help_text='Video id from Youtube', max_length=255)),
                ('video_img', models.ImageField(upload_to='videos/images/')),
                ('video_views', models.IntegerField(help_text='Number of visualizations of the video')),
                ('video_published', models.BooleanField(default=True, help_text='Determine if the video is published')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('video_playlist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.playlists')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedVideos',
            fields=[
                ('saved_video_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('saved_video_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.categories')),
                ('saved_video_playlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.playlists')),
            ],
            options={
                'verbose_name': 'SavedVideo',
                'verbose_name_plural': 'SavedVideos',
                'ordering': ['-created_at'],
            },
        ),
    ]
