# Generated by Django 3.1.3 on 2022-02-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubeimporter',
            name='yt_video_category',
        ),
    ]
