# Generated by Django 3.1.3 on 2022-02-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220212_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_yt_id',
            field=models.CharField(help_text='Video id from Youtube', max_length=255, unique=True),
        ),
    ]
