# Generated by Django 3.1.3 on 2022-02-12 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20220212_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedvideos',
            name='saved_video_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedvideos',
            name='saved_video_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories'),
        ),
        migrations.AlterField(
            model_name='savedvideos',
            name='saved_video_playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playlists'),
        ),
    ]
